name: Publish action

on:
  release:
    types: released

jobs:
  publish-action:
    runs-on: ubuntu-latest

    steps:
      - name: Publish action
        uses: actions/publish-action@v0.2.2
        with:
          source-tag: ${{ github.event.release.tag_name }}
